version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  mysql:
    container_name: sqlserver
    build:
      context: .
      dockerfile: docker/sqldump/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - 8080:8080

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATABASE="tablook"
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - 8081:8081

  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - db_data:/var/lib/csql
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra
  cassandra-web:
    image: delermando/docker-cassandra-web:v0.4.0
    ports: 
      - 3000:3000
    environment:
      - CASSANDRA_PORT=9042
      - CASSANDRA_HOST_IP=172.23.0.6
volumes:
  db_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /airportdb
      o: bind
